name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          # Copy index.html to EC2 instance (replace with actual paths)
          scp -i "C:\\Users\\test123!\\Downloads\\JETAssessment_Syifa.pem" "C:\\Users\\test123!\\Documents\\index.html" ec2-user@15.188.63.159:/var/www/html/
          
          # Restart Apache HTTP Server on EC2 instance
          ssh -i "C:\\Users\\test123!\\Downloads\\JETAssessment_Syifa.pem" ec2-user@15.188.63.159 'sudo systemctl restart httpd'
